-- Generated by fix_broken_titles.py; review before running.
-- Resolved 52 of 52 broken titles (places + place_translations, 2 statements each).

UPDATE places SET title = 'Hoành Thánh Lá Tôm Dì Mủi', updated_at = NOW() WHERE id = 'c1448f1a-22f2-4bde-9dec-882572811627'; -- was: 'Ho�nh Th�nh L� T�m D� M?i'
UPDATE place_translations SET name = 'Hoành Thánh Lá Tôm Dì Mủi', updated_at = NOW() WHERE place_id = 'c1448f1a-22f2-4bde-9dec-882572811627' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cháo Lòng Cô Ba Đakao', updated_at = NOW() WHERE id = 'fd611805-39d4-4dfa-b421-7f01667b9c61'; -- was: 'Cháo Lòng Cô Ba Đakao'
UPDATE place_translations SET name = 'Cháo Lòng Cô Ba Đakao', updated_at = NOW() WHERE place_id = 'fd611805-39d4-4dfa-b421-7f01667b9c61' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cháo lòng Phường 1', updated_at = NOW() WHERE id = '0fc82205-f274-4fb6-8d77-1044fbccfa03'; -- was: 'Cháo lòng Phường 1'
UPDATE place_translations SET name = 'Cháo lòng Phường 1', updated_at = NOW() WHERE place_id = '0fc82205-f274-4fb6-8d77-1044fbccfa03' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Lẩu cá đuối 34 - quận 2 (p An Khánh - TP.HCM)', updated_at = NOW() WHERE id = '3f36ab2a-330c-4048-ba6b-e94518a24e84'; -- was: 'Lẩu cá đuối 34 - quận 2 (p An Khánh - TP.HCM)'
UPDATE place_translations SET name = 'Lẩu cá đuối 34 - quận 2 (p An Khánh - TP.HCM)', updated_at = NOW() WHERE place_id = '3f36ab2a-330c-4048-ba6b-e94518a24e84' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Lẩu mắm 9 Tân', updated_at = NOW() WHERE id = '71a8f71b-579e-471e-8136-217d586f27d8'; -- was: 'Lẩu mắm 9 Tân'
UPDATE place_translations SET name = 'Lẩu mắm 9 Tân', updated_at = NOW() WHERE place_id = '71a8f71b-579e-471e-8136-217d586f27d8' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh Xèo Cô Bốn Bình Định', updated_at = NOW() WHERE id = '0d7b3cd9-383f-46b7-a679-74ef8ce73ccc'; -- was: 'Bánh Xèo Cô Bốn Bình Định'
UPDATE place_translations SET name = 'Bánh Xèo Cô Bốn Bình Định', updated_at = NOW() WHERE place_id = '0d7b3cd9-383f-46b7-a679-74ef8ce73ccc' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bún Thịt Nướng - Chợ Thái Bình', updated_at = NOW() WHERE id = 'ac1958d4-da92-45dd-b99f-e2e96aa1d418'; -- was: 'Bún Thịt Nướng - Chợ Thái Bình'
UPDATE place_translations SET name = 'Bún Thịt Nướng - Chợ Thái Bình', updated_at = NOW() WHERE place_id = 'ac1958d4-da92-45dd-b99f-e2e96aa1d418' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Phở Khôi Nguyên', updated_at = NOW() WHERE id = 'efc485ad-3f52-4de0-8af2-ee46e23394bf'; -- was: 'Phở Khôi Nguyên'
UPDATE place_translations SET name = 'Phở Khôi Nguyên', updated_at = NOW() WHERE place_id = 'efc485ad-3f52-4de0-8af2-ee46e23394bf' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Quán Hủ Tiếu Mì Tim Cật TRANG', updated_at = NOW() WHERE id = 'b533d5ae-0fb8-4443-aa67-e0954e818f53'; -- was: 'Quán Hủ Tiếu Mì Tim Cật TRANG'
UPDATE place_translations SET name = 'Quán Hủ Tiếu Mì Tim Cật TRANG', updated_at = NOW() WHERE place_id = 'b533d5ae-0fb8-4443-aa67-e0954e818f53' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Mì Chú Cao', updated_at = NOW() WHERE id = '9f3765d1-f175-4b50-a1e5-aa43d992e648'; -- was: 'Mì Chú Cao'
UPDATE place_translations SET name = 'Mì Chú Cao', updated_at = NOW() WHERE place_id = '9f3765d1-f175-4b50-a1e5-aa43d992e648' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Hủ tiếu mực Nghi Long', updated_at = NOW() WHERE id = '473f303d-35cd-4c91-841a-038eacb59af4'; -- was: 'Hủ tiếu mực Nghi Long'
UPDATE place_translations SET name = 'Hủ tiếu mực Nghi Long', updated_at = NOW() WHERE place_id = '473f303d-35cd-4c91-841a-038eacb59af4' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Quan chay Hoa Từ Tâm', updated_at = NOW() WHERE id = '74b4871d-064e-4cc1-a5e3-6db7e1e182f7'; -- was: 'Quan chay Hoa Từ Tâm'
UPDATE place_translations SET name = 'Quan chay Hoa Từ Tâm', updated_at = NOW() WHERE place_id = '74b4871d-064e-4cc1-a5e3-6db7e1e182f7' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Da:me Cafe', updated_at = NOW() WHERE id = '2c459ba5-0be6-47ea-817e-e398e5e37153'; -- was: 'Da:me Cafe'
UPDATE place_translations SET name = 'Da:me Cafe', updated_at = NOW() WHERE place_id = '2c459ba5-0be6-47ea-817e-e398e5e37153' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Tiệm Chang Bánh Đúc Nem Rán Hà Nội', updated_at = NOW() WHERE id = '10ea1874-fbff-4375-8af0-309fc7869427'; -- was: 'Tiệm Chang Bánh Đúc Nem Rán Hà Nội'
UPDATE place_translations SET name = 'Tiệm Chang Bánh Đúc Nem Rán Hà Nội', updated_at = NOW() WHERE place_id = '10ea1874-fbff-4375-8af0-309fc7869427' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cơm hến Thanh', updated_at = NOW() WHERE id = '544ff0b6-26b4-41cd-86e6-9d6f1b874159'; -- was: 'Cơm hến Thanh'
UPDATE place_translations SET name = 'Cơm hến Thanh', updated_at = NOW() WHERE place_id = '544ff0b6-26b4-41cd-86e6-9d6f1b874159' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cơm hến 05 hàn mặc tử. Cơm hến, bún hến, bánh lọc, bánh Nậm', updated_at = NOW() WHERE id = '9324482b-6a62-405c-b34f-b68e0afd9991'; -- was: 'Cơm hến 05 hàn mặc tử. Cơm hến, bún hến, bánh lọc, bánh Nậm'
UPDATE place_translations SET name = 'Cơm hến 05 hàn mặc tử. Cơm hến, bún hến, bánh lọc, bánh Nậm', updated_at = NOW() WHERE place_id = '9324482b-6a62-405c-b34f-b68e0afd9991' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cơm hến Hương Xưa', updated_at = NOW() WHERE id = 'e27fe67a-7bbe-43ad-9285-20a675c1f6ff'; -- was: 'Cơm hến Hương Xưa'
UPDATE place_translations SET name = 'Cơm hến Hương Xưa', updated_at = NOW() WHERE place_id = 'e27fe67a-7bbe-43ad-9285-20a675c1f6ff' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Quán Cháo Đậu Cà Đào Duy Từ', updated_at = NOW() WHERE id = '833c65d5-a3b3-4927-bc66-6fac27879c24'; -- was: 'Quán Cháo Đậu Cà Đào Duy Từ'
UPDATE place_translations SET name = 'Quán Cháo Đậu Cà Đào Duy Từ', updated_at = NOW() WHERE place_id = '833c65d5-a3b3-4927-bc66-6fac27879c24' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Nộm Bố Già', updated_at = NOW() WHERE id = 'c1b5d053-fa22-485d-8d29-07184f88c13b'; -- was: 'Nộm Bố Già'
UPDATE place_translations SET name = 'Nộm Bố Già', updated_at = NOW() WHERE place_id = 'c1b5d053-fa22-485d-8d29-07184f88c13b' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh Xèo - Nem Lụi Đà Nẵng 91 Bế Văn Đàn', updated_at = NOW() WHERE id = 'd445eb86-5b7b-4c86-839a-5de497e978b2'; -- was: 'Bánh Xèo - Nem Lụi Đà Nẵng 91 Bế Văn Đàn'
UPDATE place_translations SET name = 'Bánh Xèo - Nem Lụi Đà Nẵng 91 Bế Văn Đàn', updated_at = NOW() WHERE place_id = 'd445eb86-5b7b-4c86-839a-5de497e978b2' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh cuốn gia truyền', updated_at = NOW() WHERE id = '32550652-ba7d-4de0-94a5-a875b8d7f320'; -- was: 'Bánh cuốn gia truyền'
UPDATE place_translations SET name = 'Bánh cuốn gia truyền', updated_at = NOW() WHERE place_id = '32550652-ba7d-4de0-94a5-a875b8d7f320' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Pho Ga 26', updated_at = NOW() WHERE id = '78a39607-a7d5-452f-8128-8f0a7ce6f482'; -- was: 'Pho Ga 26'
UPDATE place_translations SET name = 'Pho Ga 26', updated_at = NOW() WHERE place_id = '78a39607-a7d5-452f-8128-8f0a7ce6f482' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Pho Binh', updated_at = NOW() WHERE id = 'a6e744ed-890f-4a65-8c39-73e01e51a1b7'; -- was: 'Pho Binh'
UPDATE place_translations SET name = 'Pho Binh', updated_at = NOW() WHERE place_id = 'a6e744ed-890f-4a65-8c39-73e01e51a1b7' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Phở Gà Đồi, phở bò', updated_at = NOW() WHERE id = '71977e56-b9c1-4d8a-8516-33ff47dcda12'; -- was: 'Phở Gà Đồi, phở bò'
UPDATE place_translations SET name = 'Phở Gà Đồi, phở bò', updated_at = NOW() WHERE place_id = '71977e56-b9c1-4d8a-8516-33ff47dcda12' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Phở Bà Ngoại', updated_at = NOW() WHERE id = '494a73d5-2897-432d-a4c7-5c362b988036'; -- was: 'Phở Bà Ngoại'
UPDATE place_translations SET name = 'Phở Bà Ngoại', updated_at = NOW() WHERE place_id = '494a73d5-2897-432d-a4c7-5c362b988036' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Phở Bò Lâm', updated_at = NOW() WHERE id = 'cda443ad-0290-4f5a-8a1b-b0b20543ba90'; -- was: 'Phở Bò Lâm'
UPDATE place_translations SET name = 'Phở Bò Lâm', updated_at = NOW() WHERE place_id = 'cda443ad-0290-4f5a-8a1b-b0b20543ba90' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cơm Niêu Sen Việt', updated_at = NOW() WHERE id = 'cf57940a-6026-44fb-ab54-09869fce4d17'; -- was: 'Cơm Niêu Sen Việt'
UPDATE place_translations SET name = 'Cơm Niêu Sen Việt', updated_at = NOW() WHERE place_id = 'cf57940a-6026-44fb-ab54-09869fce4d17' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Cơm Chay Phương Bối', updated_at = NOW() WHERE id = '6c1c7801-0741-4cb3-8710-f1f23bb215fc'; -- was: 'Cơm Chay Phương Bối'
UPDATE place_translations SET name = 'Cơm Chay Phương Bối', updated_at = NOW() WHERE place_id = '6c1c7801-0741-4cb3-8710-f1f23bb215fc' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Lẩu Đà Lạt - Lẩu cá Tầm Chu Gia', updated_at = NOW() WHERE id = 'f5e05a81-0083-442a-a49a-d3a510aacf16'; -- was: 'Lẩu Đà Lạt - Lẩu cá Tầm Chu Gia'
UPDATE place_translations SET name = 'Lẩu Đà Lạt - Lẩu cá Tầm Chu Gia', updated_at = NOW() WHERE place_id = 'f5e05a81-0083-442a-a49a-d3a510aacf16' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Lẩu Gà Lá É phú yên', updated_at = NOW() WHERE id = '0d03dd11-64a0-4cc7-b7ab-2dd10351e578'; -- was: 'Lẩu Gà Lá É phú yên'
UPDATE place_translations SET name = 'Lẩu Gà Lá É phú yên', updated_at = NOW() WHERE place_id = '0d03dd11-64a0-4cc7-b7ab-2dd10351e578' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Nem nướng TÂN LONG', updated_at = NOW() WHERE id = '591636a3-f053-4431-9c72-e83db8c5dc52'; -- was: 'Nem nướng TÂN LONG'
UPDATE place_translations SET name = 'Nem nướng TÂN LONG', updated_at = NOW() WHERE place_id = '591636a3-f053-4431-9c72-e83db8c5dc52' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'LA FORÊT BY STORII', updated_at = NOW() WHERE id = 'b03ebf91-38dd-4d84-b634-4ae82ae9d269'; -- was: 'LA FORÊT BY STORII'
UPDATE place_translations SET name = 'LA FORÊT BY STORII', updated_at = NOW() WHERE place_id = 'b03ebf91-38dd-4d84-b634-4ae82ae9d269' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Rừng Thông Mơ Farm & Bistro', updated_at = NOW() WHERE id = 'e7620628-c40d-4ce8-ae91-70f3e26d975c'; -- was: 'Rừng Thông Mơ Farm & Bistro'
UPDATE place_translations SET name = 'Rừng Thông Mơ Farm & Bistro', updated_at = NOW() WHERE place_id = 'e7620628-c40d-4ce8-ae91-70f3e26d975c' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Hồ Nuôi Cá Tầm Anh Thuỷ', updated_at = NOW() WHERE id = '4dc26391-8d9c-45ff-a5e2-dfe772dc8407'; -- was: 'Hồ Nuôi Cá Tầm Anh Thuỷ'
UPDATE place_translations SET name = 'Hồ Nuôi Cá Tầm Anh Thuỷ', updated_at = NOW() WHERE place_id = '4dc26391-8d9c-45ff-a5e2-dfe772dc8407' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Hương Quê Quán', updated_at = NOW() WHERE id = '38e8a21d-f0f7-4f36-bc13-4fcb9fd55f77'; -- was: 'Hương Quê Quán'
UPDATE place_translations SET name = 'Hương Quê Quán', updated_at = NOW() WHERE place_id = '38e8a21d-f0f7-4f36-bc13-4fcb9fd55f77' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Xẻng Nướng & Bia', updated_at = NOW() WHERE id = 'ddbeb5c9-c2df-48e1-a1e7-ac4cf9c9ba05'; -- was: 'Xẻng Nướng & Bia'
UPDATE place_translations SET name = 'Xẻng Nướng & Bia', updated_at = NOW() WHERE place_id = 'ddbeb5c9-c2df-48e1-a1e7-ac4cf9c9ba05' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'HỦ TIẾU MỰC A BỔ', updated_at = NOW() WHERE id = 'ee02934d-9288-46fd-9895-119d5cb02a23'; -- was: 'HỦ TIẾU MỰC A BỔ'
UPDATE place_translations SET name = 'HỦ TIẾU MỰC A BỔ', updated_at = NOW() WHERE place_id = 'ee02934d-9288-46fd-9895-119d5cb02a23' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Điểm tâm Tùng', updated_at = NOW() WHERE id = '9d6d935d-6e2f-4509-bb83-783709fcc7bc'; -- was: 'Điểm tâm Tùng'
UPDATE place_translations SET name = 'Điểm tâm Tùng', updated_at = NOW() WHERE place_id = '9d6d935d-6e2f-4509-bb83-783709fcc7bc' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Sam Kitchen', updated_at = NOW() WHERE id = 'd462d3c5-b12c-4f6b-ba9b-e70a120d47c1'; -- was: 'Sam Kitchen'
UPDATE place_translations SET name = 'Sam Kitchen', updated_at = NOW() WHERE place_id = 'd462d3c5-b12c-4f6b-ba9b-e70a120d47c1' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Nhà Hàng Chay Bảo Lộc', updated_at = NOW() WHERE id = '57745bad-07f3-4093-8ab9-5f900eb28657'; -- was: 'Nhà Hàng Chay Bảo Lộc'
UPDATE place_translations SET name = 'Nhà Hàng Chay Bảo Lộc', updated_at = NOW() WHERE place_id = '57745bad-07f3-4093-8ab9-5f900eb28657' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Quán phở Uyên', updated_at = NOW() WHERE id = 'edc33101-02eb-47d0-b9af-7f23784dedac'; -- was: 'Quán phở Uyên'
UPDATE place_translations SET name = 'Quán phở Uyên', updated_at = NOW() WHERE place_id = 'edc33101-02eb-47d0-b9af-7f23784dedac' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh căn Lệ', updated_at = NOW() WHERE id = '9053a82c-a860-44bf-baf3-d33282a62583'; -- was: 'Bánh căn Lệ'
UPDATE place_translations SET name = 'Bánh căn Lệ', updated_at = NOW() WHERE place_id = '9053a82c-a860-44bf-baf3-d33282a62583' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh bèo Bà Hường', updated_at = NOW() WHERE id = 'ac82cbf4-07ec-4127-9d3d-4a5cdc0d8c51'; -- was: 'Bánh bèo Bà Hường'
UPDATE place_translations SET name = 'Bánh bèo Bà Hường', updated_at = NOW() WHERE place_id = 'ac82cbf4-07ec-4127-9d3d-4a5cdc0d8c51' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bánh Tráng nướng Dì Đinh', updated_at = NOW() WHERE id = '0f22090a-a2f9-402d-9f40-8ce3e17fb84b'; -- was: 'Bánh Tráng nướng Dì Đinh'
UPDATE place_translations SET name = 'Bánh Tráng nướng Dì Đinh', updated_at = NOW() WHERE place_id = '0f22090a-a2f9-402d-9f40-8ce3e17fb84b' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Tiệm Gà Lưng Chừng Đồi', updated_at = NOW() WHERE id = '9b5f15ba-2959-42f5-9706-a91d7d550821'; -- was: 'Tiệm Gà Lưng Chừng Đồi'
UPDATE place_translations SET name = 'Tiệm Gà Lưng Chừng Đồi', updated_at = NOW() WHERE place_id = '9b5f15ba-2959-42f5-9706-a91d7d550821' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Adventure Restaurant', updated_at = NOW() WHERE id = '5561d70f-2196-4f62-8be2-281ca8184112'; -- was: 'Adventure Restaurant'
UPDATE place_translations SET name = 'Adventure Restaurant', updated_at = NOW() WHERE place_id = '5561d70f-2196-4f62-8be2-281ca8184112' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Gác Bếp Cuisine - Food & Drink', updated_at = NOW() WHERE id = '58bc838d-4d73-4623-8255-0f1fcb0325ee'; -- was: 'Gác Bếp Cuisine - Food & Drink'
UPDATE place_translations SET name = 'Gác Bếp Cuisine - Food & Drink', updated_at = NOW() WHERE place_id = '58bc838d-4d73-4623-8255-0f1fcb0325ee' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Nhà Hàng CND - Lẩu gà đen - Lẩu thắng cố - Lẩu cá tầm - Thắng cố Ngựa', updated_at = NOW() WHERE id = '973ae21f-f4c5-4c1d-83fc-6b102eaa2f59'; -- was: 'Nhà Hàng CND - Lẩu gà đen - Lẩu thắng cố - Lẩu cá tầm - Thắng cố Ngựa'
UPDATE place_translations SET name = 'Nhà Hàng CND - Lẩu gà đen - Lẩu thắng cố - Lẩu cá tầm - Thắng cố Ngựa', updated_at = NOW() WHERE place_id = '973ae21f-f4c5-4c1d-83fc-6b102eaa2f59' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Mộc quán Seafood Nha Trang', updated_at = NOW() WHERE id = '78237cf3-6f82-4923-80f1-46b7b8129eb3'; -- was: 'Mộc quán Seafood Nha Trang'
UPDATE place_translations SET name = 'Mộc quán Seafood Nha Trang', updated_at = NOW() WHERE place_id = '78237cf3-6f82-4923-80f1-46b7b8129eb3' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Nem Nướng Cô Bảy - Tp Nha Trang', updated_at = NOW() WHERE id = '93d5a5f6-b792-4563-9df6-6029b459f9be'; -- was: 'Nem Nướng Cô Bảy - Tp Nha Trang'
UPDATE place_translations SET name = 'Nem Nướng Cô Bảy - Tp Nha Trang', updated_at = NOW() WHERE place_id = '93d5a5f6-b792-4563-9df6-6029b459f9be' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'NEM NƯỚNG MĨ AN-Nem Phần và Bún Thịt Nướng', updated_at = NOW() WHERE id = '9166e68c-9f36-413f-8894-b068bc92839f'; -- was: 'NEM NƯỚNG MĨ AN-Nem Phần và Bún Thịt Nướng'
UPDATE place_translations SET name = 'NEM NƯỚNG MĨ AN-Nem Phần và Bún Thịt Nướng', updated_at = NOW() WHERE place_id = '9166e68c-9f36-413f-8894-b068bc92839f' AND locale = 'vi' AND translation_source = 'LEGACY';
UPDATE places SET title = 'Bún Thịt Nướng - Nem Ninh Hoà CÔ PHƯỚC', updated_at = NOW() WHERE id = 'b62879d6-be94-4f01-ac1a-1423cb0e40c2'; -- was: 'Bún Thịt Nướng - Nem Ninh Hoà CÔ PHƯỚC'
UPDATE place_translations SET name = 'Bún Thịt Nướng - Nem Ninh Hoà CÔ PHƯỚC', updated_at = NOW() WHERE place_id = 'b62879d6-be94-4f01-ac1a-1423cb0e40c2' AND locale = 'vi' AND translation_source = 'LEGACY';
